### ISSUE TITLE
Simple GUI frontend (Qt)

### ISSUE THREAD

**Issue by olear** [rcspam/audio2ascii#1]
Hi, a simple GUI would be nice. Can help add in Qt if you want (a simple qt wrapper over sox).

Btw, the actual bash script is missing in the repo ;)

**Comment by rcspam** [comment]
Push it on github does'nt work*. I try to undetstand git command and i have no time to do that:))

**Comment by olear** [comment]
That's ok :)

**Comment by rcspam** [comment]
I'm not a c++/c devel, but i can add yad/zenity in scripts to have a gui

**Comment by rcspam** [comment]
You know the command line push it ?

**Comment by rcspam** [comment]
It's ok now !!

**Comment by olear** [comment]
Good.

I can make the framework for a qt app that uses sox from the "commandline", that way you get a GUI and the app can be used on Windows etc.

**Comment by rcspam** [comment]
When you think this can be work!
In the meantime i can add some yad/zenity in the scripts to have a GUI on linux

**Comment by olear** [comment]
Have some hours free, will start a qt project on my fork, and will push when ready.

A zenity wrapper would be nice if you have the time.

**Comment by rcspam** [comment]
That's made with yad gui.
But how many time between the git add command and github is updated !!

**Comment by rcspam** [comment]
@olear: Ok it's update on github, can you test please and tell me if it's ok !
https://github.com/rcspam/audio2ascii/releases/tag/0.3

**Comment by olear** [comment]
Hi, just got back from a meeting. Will test your version, will also finish the qt stuff, finally got some hours free again :)

**Comment by olear** [comment]
got a working qt gui: https://github.com/olear/audio2ascii

Will add some more ui features before doing a pull request.

**Comment by rcspam** [comment]
Some improve: https://github.com/rcspam/audio2ascii/releases/tag/0.4
