### ISSUE TITLE
stop in viewer = stop audio

### ISSUE THREAD

**Issue by olear** [rcspam/audio2ascii#5]
Every time I test the audio playback I press the stop button in the viewer (pure instinct), this stops the video, but audio2asii continues, any possibility to listen on viewer signals and kill ffplay if stop?

btw, the playback works really good :)

**Comment by olear** [comment]
a super bonus would be to also listen on viewer play signal so that the viewer triggers the audio playback.

**Comment by rcspam** [comment]
I know, me too, but now it's ok !! ;)
Wait... I have an idea about play button, i test and go back...

**Comment by rcspam** [comment]
Argh!
Apparently there no Python variable on viewer, so at the moment, i don't know how do that !!

**Comment by olear** [comment]
Too bad ...

**Comment by rcspam** [comment]
Is the audio editor stay setting if you relaunch Natron ?

**Comment by olear** [comment]
Not tested, will check

**Comment by olear** [comment]
yes

**Comment by rcspam** [comment]
Passed one hour on config manager this morning to make it works. Now can put what we 'll need in it !

**Comment by olear** [comment]
Nice. Currently looking into ffplay in windows.

**Comment by rcspam** [comment]
Problem with space !!

**Comment by olear** [comment]
btw, if you adapt to this http://stackoverflow.com/a/20218672 , then you don't need three different methods to start ffplay.

**Comment by rcspam** [comment]
Yes seems cool :)

**Comment by rcspam** [comment]
subprocess make start sync too slow, so not the good solution.

**Comment by olear** [comment]
hmm, ok will try to find another solution for windows.

**Comment by rcspam** [comment]
An other problem is windows open a term when launch command line exe which waist some time...peharps same without 'subprocess' class, i dont't know.

**Comment by rcspam** [comment]
For now, no possible to interact most with viewer transport https://github.com/MrKepzie/Natron/issues/755#issuecomment-123260652

**Comment by rcspam** [comment]
For "backgrounded" ffplay on windows, perhaps should we be looking at a ffmpeg/python class

**Comment by rcspam** [comment]
No simple ffmpeg python found. Some exist but not user-friendly to install !

**Comment by olear** [comment]
Will find a solution, worst case I add it to the audiocurve bin.

**Comment by rcspam** [comment]
I didn't know you can start a win32 exec in background from qt/c++ !! So it's cool ! I thought it was  recurrent problem !

**Comment by rcspam** [comment]
Have you a facebook accout ? I have not and @blackearth2014 has a [FB page](https://www.facebook.com/groups/NatronNation/) to promote Natron, if you have you can add some link for our PyPlugins, more tester is better !

**Comment by olear** [comment]
Have an account, but not used in in a years or longer ... And have no big plans to login :)

**Comment by rcspam** [comment]
too bad !

**Comment by rcspam** [comment]
I had added a red  'when play' icon in thinking to your first comment !

**Comment by rcspam** [comment]
Can you [implement it](https://github.com/rcspam/audio2ascii/issues/5#issuecomment-123415787)  in the 'windows audiocurve exe', i haven't found a satisfying solution to do that directly in the PyPlug.

**Comment by rcspam** [comment]
Tested missing above:

[i don't no] Vocoder
[0] Reverbtron 
[0] Echotron
[0] StereoHarm - no midi - like 'harmonizer' doesn't work, but a little btw interval r/l -0.9 and 0.9
[1] CompBand 
[1] Opticaltrem 
[1] Vibe 
[1] Infinity
[0] StompBox-fuzz  - high cpu (100% 1 core ), output 'blinking'- Analisis crash Ardour 4.1

Regards

**Comment by rcspam** [comment]
@olear 
Hope migration to natron.fr is not too hard. Have you seen the comment above, i want to benefit of my vacation to finish this plugin, just yet this windows stuff so... if you have some times... Thanks

**Comment by olear** [comment]
Will help do the Windows stuff, currently on a Linux-only workstation, but may have some spare time this weekend (I hope, got several TODOs in Arena and Natron, and other work related stuff).

**Comment by rcspam** [comment]
:+1:  CU
